#!/bin/sh

# If dns service is already running, do nothing
N=$(ps -e | grep duckdns | wc -l)

# -gt "2" since subshell gives spwn to one more instance of duckdns process?
if [ "$N" -gt "2" ]; then
	exit
fi

IP="$(curl ifconfig.me)"
curl https://www.duckdns.org/update?domains=mircas\&token=TOKEN >> ~/.duckdns.log

while true; do
	sleep 5m;
	NEW_IP="$(curl ifconfig.me)";
	printf '%s\n%s%s\n%s%s\n' \
		"$(date)" "Old IP: " "$IP" "New IP: " "$NEW_IP"  >> ~/.duckdns.log
	if [ "$NEW_IP" != "$IP" ]; then
		curl https://www.duckdns.org/update?domains=mircas\&token=TOKEN >> ~/.duckdns.log
		printf '%s\n' "New IP! $NEW_IP" >> ~/.duckdns.log
		IP="$NEW_IP"
	fi
done
