#!/bin/sh

IP="$(curl ifconfig.me)"

while true; do
	sleep 5m;
	NEW_IP="$(curl ifconfig.me)";
	printf '%s\n%s%s\n%s%s\n' \
		"$(date)" "Old IP: " "$IP" "New IP: " "$NEW_IP"  >> ~/.duckdns.log
	if [ "$NEW_IP" != "$IP" ]; then
		curl https://www.duckdns.org/update?domains=mircas\&token=TOKEN >> ~/.duckdns.log
	fi
done
