#!/bin/sh

ACTIVE="$HOME/.trackme/active"
BATTERY="/sys/class/power_supply/BAT0"

setName()
{
  xsetroot -name " $WORKING | W: ${CONNECTED} | ${BAT} | $(date)"
  sleep 2
}

while true; do
  if [ -f "$ACTIVE" ];then
  	  WORKING="Working at $(sed -n 2p $ACTIVE)"
  else
  	  WORKING="Not working atm..."
  fi

  CONNECTED=$(nmcli connection show --active | tail -n1 | cut -f1 -d' ')
  if [ -z "$CONNECTED" ]; then
  	  CONNECTED="Offline"
  fi

  if [ ! -f "$BATTERY/status" ]; then
  	  BAT="No battery present"
  	  setName
  	  continue
  fi

  quota="$(( $(cat $BATTERY/capacity) / 10))"

  if [ "$(cat $BATTERY/status)" = "Discharging" ]; then
    case $quota in
      "0")
        BAT="[----------]"
        setName
        BAT="[--------- ]"
        setName
        BAT="[--------  ]"
        setName
        BAT="[-------   ]"
        setName
        BAT="[------    ]"
        setName
        BAT="[-----     ]"
        setName
        BAT="[----      ]"
        setName
        BAT="[---       ]"
        setName
        BAT="[--        ]"
        setName
        BAT="[-         ]"
        setName
        BAT="[          ]"
        setName
      ;;
   
      "1")
        BAT="[#---------]"
        setName
        BAT="[#-------- ]"
        setName
        BAT="[#-------  ]"
        setName
        BAT="[#------   ]"
        setName
        BAT="[#-----    ]"
        setName
        BAT="[#----     ]"
        setName
        BAT="[#---      ]"
        setName
        BAT="[#--       ]"
        setName
        BAT="[#-        ]"
        setName
        BAT="[#         ]"
        setName
      ;;
      "2")
        BAT="[##--------]"
        setName
        BAT="[##------- ]"
        setName
        BAT="[##------  ]"
        setName
        BAT="[##-----   ]"
        setName
        BAT="[##----    ]"
        setName
        BAT="[##---     ]"
        setName
        BAT="[##--      ]"
        setName
        BAT="[##-       ]"
        setName
        BAT="[##        ]"
        setName
      ;;
      "3")
        BAT="[###-------]"
        setName
        BAT="[###------ ]"
        setName
        BAT="[###-----  ]"
        setName
        BAT="[###----   ]"
        setName
        BAT="[###---    ]"
        setName
        BAT="[###--     ]"
        setName
        BAT="[###-      ]"
        setName
        BAT="[###       ]"
        setName
      ;;
      "4")
        BAT="[####------]"
        setName
        BAT="[####----- ]"
        setName
        BAT="[####----  ]"
        setName
        BAT="[####---   ]"
        setName
        BAT="[####--    ]"
        setName
        BAT="[####-     ]"
        setName
        BAT="[####      ]"
        setName
      ;;
      "5")
        BAT="[#####-----]"
        setName
        BAT="[#####---- ]"
        setName
        BAT="[#####---  ]"
        setName
        BAT="[#####--   ]"
        setName
        BAT="[#####-    ]"
        setName
        BAT="[#####     ]"
        setName
      ;;
      "6")
        BAT="[######----]"
        setName
        BAT="[######--- ]"
        setName
        BAT="[######--  ]"
        setName
        BAT="[######-   ]"
        setName
        BAT="[######    ]"
        setName
      ;;
      "7")
        BAT="[#######---]"
        setName
        BAT="[#######-- ]"
        setName
        BAT="[#######-  ]"
        setName
        BAT="[#######   ]"
        setName
      ;;
      "8")
        BAT="[########--]"
        setName
        BAT="[########- ]"
        setName
        BAT="[########  ]"
        setName
      ;;
      "9")
        BAT="[#########-]"
        setName
        BAT="[######### ]"
        setName
      ;;
      "10")
        BAT="[**********]"
        setName
      ;;
      *)
        BAT="FULLY CHARGED"
        setName
      ;;
    esac
  else
    case $quota in
      "0")
        BAT="[          ]"
        setName
        BAT="[+         ]"
        setName
        BAT="[++        ]"
        setName
        BAT="[+++       ]"
        setName
        BAT="[++++      ]"
        setName
        BAT="[+++++     ]"
        setName
        BAT="[++++++    ]"
        setName
        BAT="[+++++++   ]"
        setName
        BAT="[++++++++  ]"
        setName
        BAT="[+++++++++ ]"
        setName
        BAT="[++++++++++]"
        setName
      ;;
      "1")
        BAT="[#         ]"
        setName
        BAT="[#+        ]"
        setName
        BAT="[#++       ]"
        setName
        BAT="[#+++      ]"
        setName
        BAT="[#++++     ]"
        setName
        BAT="[#+++++    ]"
        setName
        BAT="[#++++++   ]"
        setName
        BAT="[#+++++++  ]"
        setName
        BAT="[#++++++++ ]"
        setName
        BAT="[#+++++++++]"
        setName
      ;;
      "2")
        BAT="[##        ]"
        setName
        BAT="[##+       ]"
        setName
        BAT="[##++      ]"
        setName
        BAT="[##+++     ]"
        setName
        BAT="[##++++    ]"
        setName
        BAT="[##+++++   ]"
        setName
        BAT="[##++++++  ]"
        setName
        BAT="[##+++++++ ]"
        setName
        BAT="[##++++++++]"
        setName
      ;;
      "3")
        BAT="[###       ]"
        setName
        BAT="[###+      ]"
        setName
        BAT="[###++     ]"
        setName
        BAT="[###+++    ]"
        setName
        BAT="[###++++   ]"
        setName
        BAT="[###+++++  ]"
        setName
        BAT="[###++++++ ]"
        setName
        BAT="[###+++++++]"
        setName
      ;;
      "4")
        BAT="[####      ]"
        setName
        BAT="[####+     ]"
        setName
        BAT="[####++    ]"
        setName
        BAT="[####+++   ]"
        setName
        BAT="[####++++  ]"
        setName
        BAT="[####+++++ ]"
        setName
        BAT="[####++++++]"
        setName
      ;;
      "5")
        BAT="[#####     ]"
        setName
        BAT="[#####+    ]"
        setName
        BAT="[#####++   ]"
        setName
        BAT="[#####+++  ]"
        setName
        BAT="[#####++++ ]"
        setName
        BAT="[#####+++++]"
        setName
      ;;
      "6")
        BAT="[######    ]"
        setName
        BAT="[######+   ]"
        setName
        BAT="[######++  ]"
        setName
        BAT="[######+++ ]"
        setName
        BAT="[######++++]"
        setName
      ;;
      "7")
        BAT="[#######   ]"
        setName
        BAT="[#######+  ]"
        setName
        BAT="[#######++ ]"
        setName
        BAT="[#######+++]"
        setName
      ;;
      "8")
        BAT="[########  ]"
        setName
        BAT="[########+ ]"
        setName
        BAT="[########++]"
        setName
      ;;
      "9")
        BAT="[######### ]"
        setName
        BAT="[#########+]"
        setName
      ;;
      "10")
       	BAT="[**********]"
       setName
      ;;
      *)
        BAT="[FULLY CHARGED]"
        setName
      ;;
    esac
  fi
done
