#!/bin/sh
Type=$1
Session=-new-$Type
Ans="$(sed -n 'n;p' ~/.bookmarks | dmenu -i)"

if [ "$Ans" = "Private" ]; then
    Session="-private-window"
    Ans="$(sed -n 'n;p' ~/.bookmarks | sed -n '/Private/!p' | sed -n '/AddBookmark/!p' |  dmenu -i)"
fi

 if [ "$Ans" = "AddBookmark" ]; then
     Name="$(echo "Input name of bookmark" | dmenu)"
     if [ -n "$Name" ]; then
         URL="$(echo "Input URL of bookmark" | dmenu)"
         if [ -n "$URL" ]; then
             printf '%s\n%s\n' "$Name" "$URL" >> ~/.bookmarks
         fi
     fi
     exit
 elif [ "$Ans" = "Search" ]; then
     Search="$(echo "Input search phrase" | dmenu | sed 's/ /+/g')"
     if [ -n "$Search" ]; then
        printf '%s' "firefox $Session https://www.duckduckgo.com/?q=$Search"
    fi
 elif [ -n  "$Ans" ]
 then
     if [ -z "$(sed -n '/^$Ans$/ {n;p;}' ~/.bookmarks)" ]; then
        printf '%s' "firefox $Session $Ans"
    else
        printf '%s' "firefox $Session $(sed -n "/^$Ans$/ {n;p}" ~/.bookmarks)"
    fi
fi
