#!/bin/bash
# Find what screen(s) are present
INTERNAL_SCREEN=$(xrandr|grep "primary"|cut -d " " -f 1)
EXTERNAL_SCREEN=$(xrandr|grep " connected"|grep -v "primary"|cut -d " " -f 1)

hdmi() {
xrandr --output $INTERNAL_SCREEN $1 $3 $4 --output $EXTERNAL_SCREEN $2 
random_background
}

case $1 in 
  off) hdmi --auto --off ;; 
  "+") hdmi --auto --auto --below $EXTERNAL_SCREEN ;;
  *) hdmi --off --auto ;;
esac
