#!/bin/sh 

night_mode() { 
#  for disp in $(xrandr | sed -n 's/^\([^ ]*\).*\<connected>.*/\1/p'); do 
#    xrandr --output $disp --gamma $1 --brightness $2 
    xrandr --output eDP1 --gamma $1 --brightness $2 
#  done } 
}
case $1 in 
  off) night_mode 1:1:1 1.0 ;; 
  *) night_mode 1:1:0.8 0.7 ;;
esac
