#!/bin/sh

# Pass is a dmenu wrapper script around pash

# Set up environment
PASH=~/Git/pash/pash

# Main


PASSWD=$($PASH l | dmenu -i -l 80)
[ -n "$PASSWD" ] && st -t "scratchpad" -g 60x20 $PASH c $PASSWD
