#!/bin/sh

# Pass is a dmenu wrapper script around pash

# Set up environment
PASH=~/Git/pash/pash

# Main


PASSWD=$($PASH l | dmenu -i -l 80)
[ -n "$PASSWD" ] && xterm -class FLOATING -e "$PASH s $PASSWD | xsel -i"

{
	sleep 15s && xsel -d
} &
