#!/bin/bash

# This script chooses a random background from $PIC_DIR

PIC_DIR=~/Pic/wallpapers/

NUM=$(find $PIC_DIR -type f | wc -l)

let "NEW = $RANDOM % $NUM + 1"

PIC=$(find $PIC_DIR -type f | sed ${NEW}p -n)

xwallpaper --zoom $PIC
