#!/bin/bash

# Set a remider for a specified time.
echo "What shall I remind you about?"
read WHAT
echo "Ok, when shall I remind you?"
read DATE

# Verify date
if [ $(echo $DATE | head -c 1) = "+" ]; then
    NOW=$(date +%s)
    DIFF=$(expr $(echo $DATE | sed s/+//) \* 60)
    SUM=$(expr $NOW + $DIFF)
    DATE=$(date -d @$SUM | head -c 16)
else
    DATE=$(date -d $DATE | head -c 16)
fi

echo "-------------------"
echo "Will remind you on:"
echo $DATE
echo "about $WHAT"
echo "-------------------"

# Check regulary if now is the time
while true; do
    if [[ $(date | head -c 16) == $DATE ]]; then
        mplayer "/home/blaklinten/Musik/Dip Da Dee Da Dee Da Doh Doh.mp3"&
        xmessage $WHAT -center
        pkill mplayer
        break
    fi
    sleep 30s
done
