#!/bin/bash

# Set a remider for a specified time.
echo "What shall I remind you about?"
read WHAT
echo "Ok, when shall I remind you?"
read DATE

# Verify date
DATE=$(date -d $DATE | head -c 16)

echo "-------------------"
echo "Will remind you on:"
echo $DATE
echo "about $WHAT"
echo "-------------------"

# Check regulary if now is the time
while true; do
    if [[ $(date | head -c 16) == $DATE ]]; then
        mplayer "/home/blaklinten/Musik/Dip Da Dee Da Dee Da Doh Doh.mp3"
        xmessage $WHAT -center
        pkill mpv
        break
    fi
    sleep 30s
done
