#!/bin/bash

# A script that shuffles all songs in a directory

trap "pkill mpv; pkill shuffle; exit;" SIGINT 

DIR_TO_PLAY="$1"

SONG=""

stop_looping()
{
  if [ -e CURRENT_MPV_LOOP ];then
    kill "$(cat CURRENT_MPV_LOOP)"
    rm CURRENT_MPV_LOOP
  fi
}

stop_playing()
{
  pkill mpv
}

play_random_song()
{
  if [ -d "$DIR_TO_PLAY" ];then
    SONG="$(find "$DIR_TO_PLAY" -type f | shuf -n1)"
  elif [ "$DIR_TO_PLAY" = "fav" ];then
    SONG="$(shuf -n1 ~/.shuffle_favorites)"
  fi
  echo "Playing song $SONG"
  mpv "$SONG" 2&> /dev/null
}

random_loop()
{
  if [ ! -e CURRENT_MPV_LOOP ]; then
    touch CURRENT_MPV_LOOP
    while [ -e CURRENT_MPV_LOOP ]; do
      play_random_song
    done &
    echo "$!" > CURRENT_MPV_LOOP
  fi
}

choose_song()
{
  if [ -d "$DIR_TO_PLAY" ];then
    SONG="$(find "$DIR_TO_PLAY" -type f | dmenu -i -p "Choose a song to play:" -l 30)"
  elif [ "$DIR_TO_PLAY" = "fav" ];then
    SONG="$(cat ~/.shuffle_favorites | dmenu -i -p "Choose a song to play:" -l 30)"
  fi
  stop_looping
  stop_playing
  {
    echo "Playing song $SONG"
    mpv "$SONG" 2&> /dev/null
    random_loop
  } &
}

add_favorite()
{
  echo "Adding current song $SONG to favorites!"
  echo "$SONG" >> ~/.shuffle_favorites
}

if [ -e CURRENT_MPV_LOOP ];then
  echo "Cleaning up after last session. Did it crash?"
  rm -v CURRENT_MPV_LOOP
fi

echo "Choose a song to play (c) or play a random one (p)."
while true; do
  read -r -n1 -s
  case "$REPLY" in
    "c")
      choose_song
      ;;
    "p")
      random_loop
      ;;
    "n")
      stop_playing
      ;;
    "f")
      add_favorite
      ;;
    "q")
      stop_looping
      stop_playing
      pkill shuffle
      exit
      ;;
    *)
      continue
      ;;
  esac
done
