#!/bin/bash

# A script that shuffles all songs in a directory

trap "pkill mpv; pkill shuffle; exit;" SIGINT 
SONGS="$(find "$1" -type f | wc -l)"
CONTINUE=1

while [ -n "$CONTINUE" ]; do
  ((NEXT_SONG = RANDOM % SONGS + 1))
  SONG="$(find "$1" -type f | sed -n ${NEXT_SONG}p)"
  echo "Playing $SONG"
  mpv "$SONG" 2&> /dev/null
done &

while true; do
  read -r -n1 -s
  case "$REPLY" in
    "n")
      pkill mpv
      continue
      ;;
    "q")
      unset CONTINUE
      pkill mpv 
      pkill shuffle
      exit
      ;;
    *)
      wait
  esac
done
