#!/bin/bash

# A script that shuffles all songs in a directory

trap "pkill mpv; pkill shuffle; exit;" SIGINT 
CONTINUE=1

while [ -n "$CONTINUE" ]; do
  SONG="$(find "$1" -type f | shuf | head -n1)"
  echo "Playing $SONG"
  mpv "$SONG" 2&> /dev/null
done &

while true; do
  read -r -n1 -s
  case "$REPLY" in
    "n")
      pkill mpv
      continue
      ;;
    "q")
      unset CONTINUE
      pkill mpv 
      pkill shuffle
      exit
      ;;
    *)
      continue
      ;;
  esac
done
