#!/bin/bash


#Showing free memory
echo "Memory Details:"
free
echo

#Disk space usage using df command
echo "Disk Space Utilization:"
df -mh
echo

#Connectivity Information
echo "Connectivity:"
nmcli device status
echo

#Battery Status
echo "Battery Status:"
acpi
echo

#Volume
echo "Speaker volume:"
pactl list sinks | grep Volume -m 1 | sed -e 's/^[ \t]*//' | sed -e 's/^.*Volume: //'
pactl list sinks | grep Mute -m 1 | sed -e 's/^[ \t]*//' #| sed -e 's/^.*://'
echo
