#!/bin/sh

# A small timer script

COUNT=0

while true; do
	SECONDS=$((COUNT % 60))
	MINUTES=$((COUNT / 60 % 60))
	HOURS=$((COUNT / 3600))
	echo $HOURS:$MINUTES:$SECONDS;
	COUNT=$((COUNT + 1))
	sleep 1s;
done
