#!/bin/bash


#Check what machine is running
case "$(uname -n)" in
	"x1-carbon")
		T_NAME="Synaptics TM3072-003"
		CENTER="960 540"
		;;
	"dubian")
		T_NAME="AlpsPS/2 ALPS GlidePoint"	
		CENTER="683 384"
		;; 
	"elx781653y4")
                T_NAME="ALP0018:00 044E:121B Touchpad"
                CENTER="960 540"
                ;;
esac

xinput --set-prop "$T_NAME" "libinput Tapping Enabled" 1
xinput --set-prop "$T_NAME" "libinput Natural Scrolling Enabled" 1

State=$(xinput list-props "$T_NAME" | grep "Device Enabled" | tail -c 2)

if [[ $State == "0" ]]
then
    xinput set-prop "$T_NAME" "Device Enabled" 1
    pkill unclutter
elif [[ $State == "1" ]]
then
    xinput set-prop "$T_NAME" "Device Enabled" 0
    unclutter -idle 0 -jitter 10 -root &
    xdotool mousemove $CENTER
fi
