#!/bin/sh

TRUE="0"
FALSE="1"

mount_boot()
{
    doas mount /boot
}

upgrade_system()
{
    doas pacman -Syu
}

unmount_boot()
{
    doas umount /boot
    lsblk
}

is_boot_mounted()
{
    BOOT_MOUNTPOINT="$(mount | grep 'boot')"

    if [ -n "$BOOT_MOUNTPOINT" ]; then
        return "$TRUE"
    fi

    return "$FALSE"
}

usb_is_present()
{
    UUID="$(grep 'boot' /etc/fstab | cut -d' ' -f1 | cut -d'=' -f2)"

    for device in $(lsblk -o UUID); do
        if [ "$device" = "$UUID" ]; then
            return "$TRUE" 
        fi
    done
    return "$FALSE"
}

try_mount_boot()
{
    usb_is_present
    if [ "$?" = "$TRUE" ]; then
        echo "Mounting..."
        mount_boot
    else
        echo "Correct USB drive not present -- Please insert boot USB drive and try again"
        return "$FALSE"
    fi
}

error()
{
    echo "Something went wrong :("
}

system_update ()
{
    is_boot_mounted

    if [ "$?" = "$TRUE" ]; then 
        echo "/boot is mounted, starting system upgrade..."
        upgrade_system
        if [ "$?" = "$FALSE" ]; then
            error
        fi
        unmount_boot
    else
        echo "/boot is not mounted, trying to fix..."
        try_mount_boot
        if [ "$?" = "$FALSE" ]; then 
            error
        else
            system_update
        fi
    fi
}

# Run main
system_update
