#!/bin/sh

mount_boot()
{
    doas mount /boot
}

update_system()
{
    doas pacman -Syu
}

unmount_boot()
{
    doas umount /boot
    lsblk

    BOOT="$(ls /boot)"
    if [ -n "$BOOT" ]; then
      error
      printf 'Boot contains %s, should be empty!\n' "$BOOT"
    fi
}

is_boot_mounted()
{
    BOOT_MOUNTPOINT="$(mount | grep 'boot')"

    if [ -n "$BOOT_MOUNTPOINT" ]; then
        return 0
    fi

    return 1
}

usb_is_present()
{
    UUID="$(grep 'boot' /etc/fstab | cut -d' ' -f1 | cut -d'=' -f2)"

    for device in $(lsblk -o UUID); do
        if [ "$device" = "$UUID" ]; then
            return 0
        fi
    done
    return 1
}

try_mount_boot()
{
    
    if usb_is_present; then
        echo "Mounting..."
        mount_boot
    else
        echo "Correct USB drive not present -- Please insert boot USB drive and try again"
        return 1
    fi
}

error()
{
    echo "Something went wrong :("
}

system_update ()
{
    

    if is_boot_mounted; then 
        echo "/boot is mounted, starting system upgrade..."
        
        if update_system; then
            unmount_boot
        else
            unmount_boot
            error
        fi
    else
        echo "/boot is not mounted, trying to fix..."
        
        if try_mount_boot; then 
            system_update
        else
            error
        fi
    fi
}

# Run main
system_update
