#!/bin/bash

# Set Git dir
GIT=/home/blaklinten/Git

# Go to Git dir to add, commit and push changes to remote
pushd $GIT > /dev/null
for dir in Backups Scripts; do
    pushd $dir > /dev/null
    printf "%s\n" "$dir"
    git diff
    git commit -a -m "Automated update"
    git fetch origin
    git rebase origin/master
    git push
    popd > /dev/null
done
popd > /dev/null

