#!/bin/bash

GIT=/home/blaklinten/Git/Backups/Misc/Scripts

for FILE in $(ls); do
    cp $FILE $GIT/$FILE
    pushd $GIT
    git add $FILE
    git commit -m "Automated backup of $FILE"
    popd
done
pushd $GIT
git push
popd

echo "-------------------------"
echo "- You're all backed up! -"
echo "-------------------------"
