#!/bin/sh

if [ -n "$1" ]; then
  #Set by env
  #UPLOAD_USER=""
  #UPLOAD_SERVER=""
  #UPLOAD_PORT=""
  #UPLOAD_DEST_PATH=""
  DEST="$UPLOAD_USER@$UPLOAD_SERVER:$UPLOAD_DEST_PATH"
  URL="https://$UPLOAD_SERVER/files/"
  SOURCE="$(readlink -f "$1")"

  rsync -a --chmod=u+rw,g=r,o=r -e "ssh -p $UPLOAD_PORT" "$SOURCE" "$DEST"
  printf "$URL%s\n" "${SOURCE##*/}"
else
	printf "%s\n" "Give one (1) argument!"
fi
