#!/bin/sh

if [ -n "$1" ]; then
  USER="pi"
  SERVER="blaklinten.xyz"
  PORT="6640"
  DEST_PATH="/home/pi/files/"
  DEST="$USER@$SERVER:$DEST_PATH"
  URL="https://$SERVER/files/"
  SOURCE="$(readlink -f "$1")"

  rsync -a --chmod=u+rw,g=r,o=r -e "ssh -p $PORT" "$SOURCE" "$DEST"
  printf "$URL%s\n" "${SOURCE##*/}"
else
	printf "%s\n" "Give one (1) argument!"
fi
